name: 'port-github-action'
description: 'Official Port.io GitHub Action'
author: 'port-labs <port-labs@getport.io>'
inputs:
  baseUrl:
    required: true
    description: 'Port.io API base URL'
    default: 'https://api.getport.io'
  clientId:
    required: true
    description: 'Client ID'
  clientSecret:
    required: true
    description: 'Client secret'
  operation:
    required: true
    description: 'One of the following operations: GET, UPSERT, SEARCH, BULK_UPSERT'
    default: 'UPSERT'
  query:
    required: false
    description: 'Query to be used for SEARCH operation'
  identifier:
    required: false
    description: 'The identifier of the entity'
  title:
    required: false
    description: 'The display name of the entity'
  icon:
    required: false
    description: 'The icon of the entity'
  blueprint:
    required: false
    description: 'The name of the Blueprint that the entity is based on'
  properties:
    required: false
    description: 'The metadata of the entity'
    default: '{}'
  team:
    required: false
    description: 'The teams belonging of the entity'
  relations:
    required: false
    description: 'The related entities of the entity'
  runId:
    required: false
    description: 'The Port action run id that performed the changes to the catalog'
  entities:
    required: false
    description: 'The entities to be used for BULK_UPSERT operation'
outputs:
  identifier:
    description: 'The identifier of the created entity'
  entity:
    description: 'The full JSON string entity'
  entities:
    description: 'When using SEARCH operation, this is entities array output'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-right'
  color: 'green'
