name: 'port-github-action'
description: 'Official Port.io GitHub Action'
author: 'port-labs <port-labs@getport.io>'
inputs:
  baseUrl:
    required: true
    description: 'Port.io API base URL'
    default: 'https://api.getport.io'
  clientId:
    required: true
    description: 'Client ID'
  clientSecret:
    required: true
    description: 'Client secret'
  operation:
    required: true
    description: 'One of the following operations: GET, UPSERT, SEARCH, BULK_UPSERT, CREATE_RUN, PATCH_RUN, DELETE'
    default: 'UPSERT'
  query:
    required: false
    description: 'Query to be used for SEARCH operation'
  include:
    required: false
    description: 'The properties of the entity to include in the response. Only these values will be returned in the response. Only applicable for GET and SEARCH operations. For example: properties.propertyIdentifier,identifier'
  identifier:
    required: false
    description: 'The identifier of the entity'
  title:
    required: false
    description: 'The display name of the entity'
  icon:
    required: false
    description: 'The icon of the entity'
  blueprint:
    required: false
    description: 'The name of the Blueprint that the entity is based on'
  properties:
    required: false
    description: 'The metadata of the entity'
    default: '{}'
  team:
    required: false
    description: 'The teams belonging of the entity'
  relations:
    required: false
    description: 'The related entities of the entity'
  runId:
    required: false
    description: 'The Port action run id that performed the changes to the catalog'
  entities:
    required: false
    description: 'The entities to be used for BULK_UPSERT operation'
  link:
    required: false
    description: 'The Port action link'
  summary:
    required: false
    description: 'The port action summary'
  externalRunId:
    required: false
    description: 'The port action external run id'
  status:
    required: false
    description: 'The port action status (success, failure)'
  logMessage:
    required: false
    description: 'The port action log message'
  action:
    required: false
    description: 'The port action identifier for which to create a new run'
  delete_dependents:
    required: false
    description: 'When deleting entity, this is the flag that indicates to delete dependent entities also'
    default: 'false'
  createMissingRelatedEntities:
    required: false
    description: 'When upserting entity, enables the creation of missing related entities that do not exist in the catalog yet'
    default: 'false'
outputs:
  identifier:
    description: 'The identifier of the created entity'
  identifiers:
    description: 'When using BULK_UPSERT operation, this is the identifiers array output'
  entity:
    description: 'The full JSON string entity'
  entities:
    description: 'When using SEARCH operation, this is entities array output'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'arrow-right'
  color: 'green'
