name: 'test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run build && npm test
        env:
          INPUT_BASEURL: https://api.getport.io
          INPUT_CLIENTID: ${{ secrets.PORT_INTEG_CLIENT_ID }}
          INPUT_CLIENTSECRET: ${{ secrets.PORT_INTEG_CLIENT_SECRET }}
